# Ignore everything
*

# Allow files and folders with a pattern starting with !

# cubzh/bundle
!cubzh/bundle
cubzh/bundle/shaders
!cubzh/bundle/shaders/essl

# cubzh/core
!cubzh/core/*.c
!cubzh/core/*.h

# cubzh/deps
!cubzh/deps/bgfx/bgfx/3rdparty
!cubzh/deps/bgfx/bgfx/examples/common
!cubzh/deps/bgfx/bgfx/include
!cubzh/deps/bgfx/bgfx/scripts
!cubzh/deps/bgfx/bgfx/src
!cubzh/deps/bgfx/bimg
!cubzh/deps/bgfx/bx
!cubzh/deps/deptool/cmd/deptool_linux_x86_64
!cubzh/deps/libluau/_active_/prebuilt/source
!cubzh/deps/lpng/src
!cubzh/deps/miniaudio
!cubzh/deps/xptools/common
!cubzh/deps/xptools/deps
!cubzh/deps/xptools/include
!cubzh/deps/xptools/web

# cubzh/i18n
!cubzh/i18n/*.json

# cubzh/lua/modules
!cubzh/lua/modules/*.lua

!common
!deps/gif_load/gif_load.h
!deps/hasher/linux/amd64
!deps/hasher/linux/arm64
!go/cu.bzh/cors
!go/cu.bzh/wasmserver
!wasm/Particubes
wasm/Particubes/build
# TODO: remove editions
!wasm/editions
