# run 1 worker process per CPU core available
# worker_processes auto;

events {}

http {

	resolver 127.0.0.11 ipv6=off;
    proxy_pass_request_headers on; # transmit incoming request heads
    client_max_body_size 10M; # allow incoming requests of 10M max
    underscores_in_headers on; # to remove later

	# Redirect all HTTP traffic to HTTPS
    server {
        listen 80;
        server_name ping-us.cu.bzh;
        location / {
            return 301 https://$server_name$request_uri;
        }
    }

    server {
        listen              443 ssl;
        server_name         ping-us.cu.bzh;
        ssl_certificate     /cubzh/certificates/cu.bzh.chained.crt;
        ssl_certificate_key /cubzh/certificates/cu.bzh.key;
        location / {
        	# only allow GET requests
            limit_except GET {
                deny all;
            }
            proxy_pass http://ping;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen              443 ssl;
        server_name         servers-us-1.cu.bzh;
        ssl_certificate     /cubzh/certificates/cu.bzh.chained.crt;
        ssl_certificate_key /cubzh/certificates/cu.bzh.key;
        location /servers/ {
            rewrite /servers/(.*) /$1 break;
            proxy_pass http://$1;
            proxy_read_timeout 3600s;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
