# Ignore everything
*

# Allow files and folders with a pattern starting with !
!common
!cubzh/bundle
!cubzh/core
!cubzh/deps
!cubzh/lua/modules
!cubzh/i18n
!deps
!go/cu.bzh/cors
!go/cu.bzh/wasmserver
!wasm/Particubes

# might not be needed
!wasm/www
!wasm/editions
