# run 1 worker process per CPU core available
# worker_processes auto;

events {}

http {
    # ssl_session_cache   shared:SSL:5m;
    # ssl_session_timeout 5m;

    proxy_pass_request_headers on; # transmit incoming request heads
    client_max_body_size 10M; # allow incoming requests of 10M max
    underscores_in_headers on; # to remove later

    server {
        listen              443 ssl;
        server_name         api.cu.bzh;
        ssl_certificate     /cubzh/certificates/cu.bzh.chained.crt;
        ssl_certificate_key /cubzh/certificates/cu.bzh.key;
        # ssl_protocols       TLSv1 TLSv1.1 TLSv1.2; (Note: try enabling only TLSv1.3 for enhanced security)
        # ssl_ciphers         HIGH:!aNULL:!MD5;
        # ...

        location / {
            limit_except GET HEAD POST OPTIONS PATCH DELETE {
                deny all;
            }
            proxy_pass https://hub-https:443/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen              443 ssl;
        server_name         api.particubes.com;
        ssl_certificate     /cubzh/certificates/particubes.com.chained.crt;
        ssl_certificate_key /cubzh/certificates/particubes.com.key;
        # ssl_protocols       TLSv1 TLSv1.1 TLSv1.2; (Note: try enabling only TLSv1.3 for enhanced security)
        # ssl_ciphers         HIGH:!aNULL:!MD5;
        # ...

        location / {
            limit_except GET HEAD POST OPTIONS PATCH DELETE {
                deny all;
            }
            proxy_pass https://hub-https:443/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}