#
# This is the NGINX config file for the czh-prod-wasm machine. (on AWS)
# This file is part of the Docker image for the "nginx-web" service.
#

worker_processes 1;

events {}

http {

    # Use docker DNS server to resolve hostnames
    resolver 127.0.0.11 valid=30s ipv6=off;

    # app.cu.bzh | huggingface.cu.bzh
    # ------------------------------------
    server {
        listen              443 ssl default_server;
        server_name         app.cu.bzh huggingface.cu.bzh;
        ssl_certificate     /cubzh/certificates/cu.bzh.chained.crt;
        ssl_certificate_key /cubzh/certificates/cu.bzh.key;
        location / {
            proxy_pass http://wasm;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # dashboard.cu.bzh
    # ------------------------------------
    server {
        listen              443 ssl;
        server_name         dashboard.cu.bzh;
        ssl_certificate     /cubzh/certificates/cu.bzh.chained.crt;
        ssl_certificate_key /cubzh/certificates/cu.bzh.key;
        location / {
            proxy_pass http://parentdashboard;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # files.cu.bzh
    # ------------------------------------
    server {
        listen              443 ssl;
        server_name         files.cu.bzh;
        ssl_certificate     /cubzh/certificates/cu.bzh.chained.crt;
        ssl_certificate_key /cubzh/certificates/cu.bzh.key;
        location / {
            limit_except GET OPTIONS {
                deny all;
            }
            proxy_pass http://fileserver;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # redirect any HTTP to HTTPS
    server {
        listen 80;
        server_name _;
        return 301 https://$host$request_uri;
    }
}
